#!/bin/bash
## STANDARD OUTPUT AND ERROR: ---------------
#SBATCH -o ./tjob.out.%j 
#SBATCH -e ./tjob.err.%j
## JOB NAME ---------------------------------
#SBATCH -J HUBB
## NUMBER OF NODES AND MPI TASKS PER NODE --
#SBATCH --exclusive
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
## WALL CLOCK LIMIT ------------------------
#SBATCH --time=48:00:00
#SBATCH --partition=p.7d.big

srun /home/dimauro/HUBBARD/code_current/HUBB.x < hubb.inp > hubb.out
