#!/bin/bash
## STANDARD OUTPUT AND ERROR: ---------------
#SBATCH -o ./tjob.out.%j 
#SBATCH -e ./tjob.err.%j
## INITIAL WORKING DIRECTORY ----------------
#SBATCH -D ./
## JOB NAME ---------------------------------
#SBATCH -J 3x3HF
## NUMBER OF NODES AND MPI TASKS PER NODE ---
#SBATCH --exclusive
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
## WALL CLOCK LIMIT -------------------------
#SBATCH --time=48:00:00
#SBATCH --partition=p.48h.big

srun HUBB.x < hubb.inp > hubb.out
